### ISSUE TITLE
Issues with debezium-connector-mysql on RDS

### ISSUE THREAD

**Issue by lktslionel** [eventuate-local/eventuate-local#14]
Hi,
I'm trying to use the `cdc-service` on AWS with a MySQL RDS database. When running the `cdc-service`, the application failed on step 2; when I tries to flush the database I guess. 

Below the error : 

```
017-07-03 16:48:50.533  INFO 8 --- [y-app-connector] i.d.connector.mysql.SnapshotReader       : Step 0: disabling autocommit and enabling repeatable read transactions
2017-07-03 16:48:50.554  INFO 8 --- [y-app-connector] i.d.connector.mysql.SnapshotReader       : Step 1: start transaction with consistent snapshot
2017-07-03 16:48:50.597  INFO 8 --- [y-app-connector] i.d.connector.mysql.SnapshotReader       : Step 2: flush and obtain global read lock (preventing writes to database)
2017-07-03 16:48:50.619 ERROR 8 --- [y-app-connector] i.d.connector.mysql.SnapshotReader       : Failed due to error: Aborting snapshot after running 'FLUSH TABLES WITH READ LOCK': Access denied for user 'eventuate_user'@'%' (using password: YES)

org.apache.kafka.connect.errors.ConnectException: Access denied for user 'eventuate_user'@'%' (using password: YES) Error code: 1045; SQLSTATE: 28000.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:141) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:120) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:449) [debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.sql.SQLException: Access denied for user 'eventuate_user'@'%' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:840) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:740) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at io.debezium.jdbc.JdbcConnection.lambda$execute$1(JdbcConnection.java:242) ~[debezium-core-0.3.1.jar!/:0.3.1]
	at io.debezium.jdbc.JdbcConnection.execute(JdbcConnection.java:259) ~[debezium-core-0.3.1.jar!/:0.3.1]
	at io.debezium.jdbc.JdbcConnection.execute(JdbcConnection.java:236) ~[debezium-core-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:194) [debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	... 1 common frames omitted
```

I found some[ discussion about the subject](https://groups.google.com/forum/#!topic/debezium/vM5NehxmsOI)  and I appears that there is a bug on RDS with the Debezium connector (version <0.4.1). Unfortunately, the issue seems to be [resolved with the version 0.4.1](https://issues.jboss.org/browse/DBZ-140?_sscc=t).

Could you please upgrade the version of this connector? 
Any suggestion on running the cdc on AWS ? 
Should I create a MySQL instance on EC2 to make this work; as some guys suggested ? 
 
Thank in advance
Regards

**Comment by cer** [comment]
Two things.

First, one option is to investigate whether simply switching to the latest version of Debezium will fix the problem. I just ran a quick test and it seems to work.

Second, the new-cdc directory contains a rewrite of the cdc-service that doesn't use Debezium. I haven't yet created a docker image for it, however. I plan to do that shortly.
