### ISSUE TITLE
while running with docker-compose cdc service should wait for mysql container 

### ISSUE THREAD

**Issue by fusionswap** [eventuate-local/eventuate-local#2]
When running with docker-compose, if cdc service starts before mysql is ready to accept connections, it fails to read transaction log. 
As a workaround, the cdcservice image can be built with https://github.com/vishnubob/wait-for-it/blob/master/wait-for-it.sh
Using this cdc service can wait untill mysql starts accepting connections.

The error message seen is below:

2016-12-23 07:40:09.514 ERROR 7 --- [eaderSelector-0] d.EventTableChangesToAggregateTopicRelay : In takeLeadership

java.util.concurrent.ExecutionException: java.lang.RuntimeException: Engine failed to startError while trying to run connector class 'io.debezium.connector.mysql.MySqlConnector'
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_91]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[na:1.8.0_91]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:61) [eventuate-local-java-embedded-cdc-0.6.0.RELEASE.jar!/:na]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:53) [eventuate-local-java-embedded-cdc-0.6.0.RELEASE.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:534) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239) [curator-recipes-2.11.0.jar!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.lang.RuntimeException: Engine failed to startError while trying to run connector class 'io.debezium.connector.mysql.MySqlConnector'
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$0(EventTableChangesToAggregateTopicRelay.java:155) ~[eventuate-local-java-embedded-cdc-0.6.0.RELEASE.jar!/:na]
	at io.debezium.embedded.EmbeddedEngine.fail(EmbeddedEngine.java:342) ~[debezium-embedded-0.3.1.jar!/:0.3.1]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:507) ~[debezium-embedded-0.3.1.jar!/:0.3.1]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$1(EventTableChangesToAggregateTopicRelay.java:164) ~[eventuate-local-java-embedded-cdc-0.6.0.RELEASE.jar!/:na]
	... 3 common frames omitted
Caused by: org.apache.kafka.connect.errors.ConnectException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. Error code: 0; SQLSTATE: 08S01.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:141) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:120) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:449) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	... 1 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:628) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1014) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2255) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_91]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_91]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_91]
	at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$0(JdbcConnection.java:113) ~[debezium-core-0.3.1.jar!/:0.3.1]
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:466) ~[debezium-core-0.3.1.jar!/:0.3.1]
	at io.debezium.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:212) ~[debezium-core-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:168) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	... 1 common frames omitted
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2957) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:560) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	... 20 common frames omitted

2016-12-23 07:40:09.516  INFO 7 --- [pool-5-thread-1] o.a.kafka.connect.util.KafkaBasedLog     : Stopped KafkaBasedLog for topic eventuate.local.cdc.my-sql-connector.offset.storage
2016-12-23 07:40:09.528  INFO 7 --- [pool-5-thread-1] o.a.k.c.storage.KafkaOffsetBackingStore  : Stopped KafkaOffsetBackingStore

**Comment by cer** [comment]
Thanks for trying out Eventuate. Looks like a race condition that the CDC server needs to address, i.e. keep trying to connect until MySQL is actually able to accept conections.

There might be a similar issue with connection to Kafka.
