### ISSUE TITLE
Cdcservice lost connection to mysql

### ISSUE THREAD

**Issue by bessaleh** [eventuate-local/eventuate-local#33]
Would you have any idea why cdcservice display those errors.  
this has the effect that the events are not long published

The error message seen is below: 
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Engine failed to startError while trying to run connector class 'io.debezium.connector.mysql.MySqlConnector'
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_121]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[na:1.8.0_121]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:69) [eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:61) [eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:534) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239) [curator-recipes-2.11.0.jar!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.lang.RuntimeException: Engine failed to startError while trying to run connector class 'io.debezium.connector.mysql.MySqlConnector'
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$0(EventTableChangesToAggregateTopicRelay.java:165) ~[eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	at io.debezium.embedded.EmbeddedEngine.fail(EmbeddedEngine.java:342) ~[debezium-embedded-0.3.1.jar!/:0.3.1]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:507) ~[debezium-embedded-0.3.1.jar!/:0.3.1]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$1(EventTableChangesToAggregateTopicRelay.java:174) ~[eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	... 3 common frames omitted
Caused by: org.apache.kafka.connect.errors.ConnectException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.000005' at 76930033, the last event read from './mysql-bin.000008' at 2589, the last byte read from './mysql-bin.000008' at 2589. Error code: 1236; SQLSTATE: HY000.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:141) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:111) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.BinlogReader$ReaderThreadLifecycleListener.onCommunicationFailure(BinlogReader.java:449) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:734) ~[mysql-binlog-connector-java-0.4.0.jar!/:na]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:462) ~[mysql-binlog-connector-java-0.4.0.jar!/:na]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$5.run(BinaryLogClient.java:623) ~[mysql-binlog-connector-java-0.4.0.jar!/:na]
	... 1 common frames omitted
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.000005' at 76930033, the last event read from './mysql-bin.000008' at 2589, the last byte read from './mysql-bin.000008' at 2589.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:698) ~[mysql-binlog-connector-java-0.4.0.jar!/:na]
	... 3 common frames omitted

Best regards

**Comment by lktslionel** [comment]
##### ISSUE
* Bug Report

##### COMPONENT
cdcservice

##### VERSION
eventuate-java-cdc-service-0.11.0.RELEASE.jar

##### OS / ENVIRONMENT
Docker image based on `Debian Jessie 8`

##### SUMMARY

The **cdcservice** when starting failed either to read binlog from MySQL or to push changes to Kafka. We got the following log output. 

- Any Idea of what went wrong ? 
- What does this error mean ? 

##### LOGS 

```
2018-01-16 14:35:39.392  INFO 9 --- [pool-5-thread-1] o.a.kafka.connect.util.KafkaBasedLog     : Stopping KafkaBasedLog for topic eventuate.local.cdc.my-sql-connector.offset.storage
2018-01-16 14:35:39.393  INFO 9 --- [pool-5-thread-1] o.a.k.clients.producer.KafkaProducer     : Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2018-01-16 14:35:39.395 ERROR 9 --- [eaderSelector-0] d.EventTableChangesToAggregateTopicRelay : In takeLeadership

java.util.concurrent.ExecutionException: java.lang.RuntimeException: Engine failed to startError while trying to run connector class 'io.debezium.connector.mysql.MySqlConnector'
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_121]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[na:1.8.0_121]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:69) [eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:61) [eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:534) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245) [curator-recipes-2.11.0.jar!/:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239) [curator-recipes-2.11.0.jar!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.lang.RuntimeException: Engine failed to startError while trying to run connector class 'io.debezium.connector.mysql.MySqlConnector'
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$0(EventTableChangesToAggregateTopicRelay.java:165) ~[eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	at io.debezium.embedded.EmbeddedEngine.fail(EmbeddedEngine.java:342) ~[debezium-embedded-0.3.1.jar!/:0.3.1]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:507) ~[debezium-embedded-0.3.1.jar!/:0.3.1]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$1(EventTableChangesToAggregateTopicRelay.java:174) ~[eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	... 3 common frames omitted
Caused by: org.apache.kafka.connect.errors.ConnectException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.000005' at 76930033, the last event read from './mysql-bin.000013' at 154, the last byte read from './mysql-bin.000013' at 154. Error code: 1236; SQLSTATE: HY000.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:141) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:111) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.BinlogReader$ReaderThreadLifecycleListener.onCommunicationFailure(BinlogReader.java:449) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:734) ~[mysql-binlog-connector-java-0.4.0.jar!/:na]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:462) ~[mysql-binlog-connector-java-0.4.0.jar!/:na]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$5.run(BinaryLogClient.java:623) ~[mysql-binlog-connector-java-0.4.0.jar!/:na]
	... 1 common frames omitted
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.000005' at 76930033, the last event read from './mysql-bin.000013' at 154, the last byte read from './mysql-bin.000013' at 154.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:698) ~[mysql-binlog-connector-java-0.4.0.jar!/:na]
	... 3 common frames omitted
```

Thanks in advance

**Comment by cer** [comment]
The root exception is this:

Caused by: org.apache.kafka.connect.errors.ConnectException: A slave with
the same server_uuid/server_id as this slave has connected to the master;
the first event 'mysql-bin.000005' at 76930033, the last event read from
'./mysql-bin.000008' at 2589, the last byte read from './mysql-bin.000008'
at 2589. Error code: 1236; SQLSTATE: HY000.

Please look at what other slaves are connected to the same DB. Another
running CDC?

On Jan 16, 2018 10:40 PM, "bessaleh" <notifications@github.com> wrote:

Would you have any idea why cdcservice display those errors.
this has the effect that the events are not long published

The error message seen is below:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Engine
failed to startError while trying to run connector class
'io.debezium.connector.mysql.MySqlConnector'
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
~[na:1.8.0_121]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
~[na:1.8.0_121]
at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTo
picRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:69)
[eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTo
picRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:61)
[eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
at org.apache.curator.framework.recipes.leader.LeaderSelector$
WrappedListener.takeLeadership(LeaderSelector.java:534)
[curator-recipes-2.11.0.jar!/:na]
at org.apache.curator.framework.recipes.leader.LeaderSelector.
doWork(LeaderSelector.java:399) [curator-recipes-2.11.0.jar!/:na]
at org.apache.curator.framework.recipes.leader.LeaderSelector.
doWorkLoop(LeaderSelector.java:441) [curator-recipes-2.11.0.jar!/:na]
at org.apache.curator.framework.recipes.leader.LeaderSelector.
access$100(LeaderSelector.java:64) [curator-recipes-2.11.0.jar!/:na]
at org.apache.curator.framework.recipes.leader.LeaderSelector$
2.call(LeaderSelector.java:245) [curator-recipes-2.11.0.jar!/:na]
at org.apache.curator.framework.recipes.leader.LeaderSelector$
2.call(LeaderSelector.java:239) [curator-recipes-2.11.0.jar!/:na]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[na:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[na:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[na:1.8.0_121]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.lang.RuntimeException: Engine failed to startError while
trying to run connector class 'io.debezium.connector.mysql.MySqlConnector'
at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTo
picRelay.lambda$startCapturingChanges$0(EventTableChangesToAggregateTopicRelay.java:165)
~[eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
at io.debezium.embedded.EmbeddedEngine.fail(EmbeddedEngine.java:342)
~[debezium-embedded-0.3.1.jar!/:0.3.1]
at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:507)
~[debezium-embedded-0.3.1.jar!/:0.3.1]
at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTo
picRelay.lambda$startCapturingChanges$1(EventTableChangesToAggregateTopicRelay.java:174)
~[eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
... 3 common frames omitted
Caused by: org.apache.kafka.connect.errors.ConnectException: A slave with
the same server_uuid/server_id as this slave has connected to the master;
the first event 'mysql-bin.000005' at 76930033, the last event read from
'./mysql-bin.000008' at 2589, the last byte read from './mysql-bin.000008'
at 2589. Error code: 1236; SQLSTATE: HY000.
at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:141)
~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:111)
~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
at io.debezium.connector.mysql.BinlogReader$ReaderThreadLifecycleListener.
onCommunicationFailure(BinlogReader.java:449) ~[debezium-connector-mysql-0.
3.1.jar!/:0.3.1]
at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:734)
~[mysql-binlog-connector-java-0.4.0.jar!/:na]
at com.github.shyiko.mysql.binlog.BinaryLogClient.
connect(BinaryLogClient.java:462) ~[mysql-binlog-connector-java-
0.4.0.jar!/:na]
at com.github.shyiko.mysql.binlog.BinaryLogClient$5.run(BinaryLogClient.java:623)
~[mysql-binlog-connector-java-0.4.0.jar!/:na]
... 1 common frames omitted
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: A slave
with the same server_uuid/server_id as this slave has connected to the
master; the first event 'mysql-bin.000005' at 76930033, the last event read
from './mysql-bin.000008' at 2589, the last byte read from
'./mysql-bin.000008' at 2589.
at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:698)
~[mysql-binlog-connector-java-0.4.0.jar!/:na]
... 3 common frames omitted

Best regards

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eventuate-local/eventuate-local/issues/33>, or mute the
thread

**Comment by lktslionel** [comment]
No other CDC was connected to the MySQL database. We upgraded to the `eventuate-java-cdc-service-0.12.6.RELEASE.jar` and this fixed our issues. 

It also looks like MySQL was keeping the connection as a tcp socket zombie.
Thanks anyway ;-)

**Comment by bessaleh** [comment]
Hi Chris,

After upgrading the cdc-service to eventuate-java-cdc-service-0.12.6.RELEASE.jar we still have the same problem a few days later. 

Would do you have any ideas why this issue happen?

Thanks in advance

**Comment by cer** [comment]
I am guessing that it was coincidence that the problem went away when you upgraded - or did you really see different behavior?

The cdc service is designed to reconnect when it loses a connection to MySQL. However, if MySQL is "keeping the connection as a tcp socket zombie." then that will prevent reconnection.

I need to know more about how you are deploying the application.

1. Are you running the cdcservice as a standalone service (e.g. the demos run it as a Docker container) or as simply a jar in each of your applications? Either way works but I think running the cdcservice as a separate service AND not including the CDC jar in your application is probably the most manageable approach. That way you can stop and start the CDC service more easily.
2. It would be good to see the logs from the CDC service. Previously, you sent a excerpt of the  log that showed the reconnection. What happened prior to that?

**Comment by bessaleh** [comment]
We didn't see different behaviour after upgrading the cdc service.

1. cdc service, kafka and zookeeper each one is running alone as a Docker container. When we restart the cdc-service container we still already have the same problem. 
3. The MySQL database is running on the server (not like a Docker container)  where the eventuate Docker stack: cdc service, kafka, zookeeper is running. 
We restarted many times MySQL but the cdc still had the same behaviour.
4. In our side we don't manage any connection to MySQL, so I don't khnow why the connection is keeping as a tcp socket zombie
5. Each application is running as a Docker container: cdc-service, kafka, zookeeper and all the applications which are create/read events. 

I have a question about how cdc service, kafka, zookeeper works together.

2. This is the kind of errors which is logged by cdc service: 

`[ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0x1612458c4270000 type:create cxid:0x1 zxid:0x2 txntype:-1 reqpath:n/a Error Path:/eventuatelocal/cdc/leader Error:KeeperErrorCode = NoNode for /eventuatelocal/cdc/leader`

`2018-01-16 14:35:30.121  WARN 9 --- [pool-5-thread-1] o.a.kafka.common.utils.AppInfoParser     : Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=49ec3aa6-b65b-4b22-a9fd-feb0aa7f1c43
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[na:1.8.0_121]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[na:1.8.0_121]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[na:1.8.0_121]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[na:1.8.0_121]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[na:1.8.0_121]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[na:1.8.0_121]
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:58) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:328) [kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:188) [kafka-clients-0.10.0.1.jar!/:na]
	at io.debezium.relational.history.KafkaDatabaseHistory.start(KafkaDatabaseHistory.java:147) [debezium-core-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.MySqlSchema.start(MySqlSchema.java:117) [debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.MySqlTaskContext.start(MySqlTaskContext.java:167) [debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:69) [debezium-connector-mysql-0.3.1.jar!/:0.3.1]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:450) [debezium-embedded-0.3.1.jar!/:0.3.1]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$1(EventTableChangesToAggregateTopicRelay.java:174) [eventuate-local-java-embedded-cdc-0.12.0.RELEASE.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]`

Thanks in advance

**Comment by cer** [comment]
One thing: please verify that your application doesn't include
eventuate-local-java-embedded-cdc-autoconfigure
jar. This will ensure that only the CDC service (and not the CDC code
embedded in the application) is trying to connect to MySQL. See the newly
created issue to update docs that references your issue.

**Comment by bessaleh** [comment]
Yes our applications include eventuate-local-java-embedded-cdc-autoconfigure. I removed it from build.gradle
I wish that this fix the bug :)

**Comment by cer** [comment]
Removing the CDC code from the application is a good step. It means that it's only the service container that is running the CDC code.

**Comment by cer** [comment]
What i am confused by is the lack of log messages prior to exception being thrown that is caused by 'A slave
with the same server_uuid/server_id as this slave has connected to the
master;'

I'd expect to see log messages like

```
018-02-01 05:00:21.984  INFO 1 --- [ blc-mysql:3306] i.debezium.connector.mysql.BinlogReader  : Stopped reading binlog after 0 events, no new offset was recorded
cdcservice_1         | 2018-02-01 05:00:21.990  INFO 1 --- [pool-4-thread-1] i.d.connector.mysql.MySqlConnectorTask   : Stopping MySQL connector task
cdcservice_1         | 2018-02-01 05:00:21.990  INFO 1 --- [pool-4-thread-1] i.d.connector.mysql.ChainedReader        : Stopping the binlog reader
cdcservice_1         | 
```

Or possibly log messages from `c.g.shyiko.mysql.binlog.BinaryLogClient`:

```
2018-02-01 05:00:02.938  INFO 1 --- [ blc-mysql:3306] c.g.shyiko.mysql.binlog.BinaryLogClient  : Connected to mysql:3306 at mysql-bin.000003/154 (sid:85744, cid:25)
```

**Comment by cer** [comment]
One more thing. Please clarify how you fix the problem. Do you simply restart the cdcservice container?

**Comment by cer** [comment]
Or more specifically. Earlier you had said "When we restart the cdc-service container we still already have the same problem.". Does that mean that when you restart the cdcservice it does not resume publishing events? Please clarify?

Also, if this does not fix the problem then

* What command are you using to stop the cdc service?
* What command are you using to restart the cdc service?
* What is the 'docker log' output of the restarted service?

If docker stop/rm/run (or the docker-compose equivalent) does not fix the problem and enable the CDcservice to resume processing I don't know to suggest. If a brand new CDC service container cannot connect to MySQL then that suggests that MYSQL is doing something very strange.

**Comment by bessaleh** [comment]
Where are fixing the problem by recreating the tree containers: cdc-service, kafka and zookeeper using docker-compose.
We are using `docker stop` and `docker start` or `docker restart` to stop and start the containers.
Before and after restarting cdc-service, publishing events doesn't work and cdc still log that  a slave with the same server_uuid/server_id as this slave has connected to the master;there is another.

After recreating the tree containers, all events are replied from the beginning which caused us some problems like duplications of some information.

How I can avoid this behaviours: repling events from the beginnning ?

**Comment by cer** [comment]
You should not need to restart kafka/zookeeper - that's why you are getting events from the beginning.
Stopping and starting a container doesn't actually recreate it. I wonder whether that somehow causes the network connection to linger.

What I suggest doing is stopping, removing and recreating the cdcservice only.
For example,

```
docker-compose up -d --force-recreate --no-deps cdcservice
```

Alternatively, `docker-compose stop/rm/up -d cdcservice`

**Comment by bessaleh** [comment]
I confirm that we  created the cdc container using docker -compose but it still log the same error. That's why we recreated the three containers: kafka, zookeeper and cdc.

Can I persist events cursor in (kafka, zookeeper) or using another trick to avoid getting events from the beginning ?

**Comment by cer** [comment]
Please be more specific:

1. What commands did you use to terminate and recreate the cdc container
2. Please send the log file of the newly created cdc container

**Comment by cer** [comment]
@bessaleh ?

**Comment by bessaleh** [comment]
Sorry for the delay
1- We use **docker-compose  up cdc-service  --remove-orphans --no-deps -d** command to recreate the container
2- This the first 500 lines of the newly created cdc container
[logs_500.log](https://github.com/eventuate-local/eventuate-local/files/1711425/logs_500.log)

**Comment by cer** [comment]
Two points

1. `docker-compose up cdc-service` does nothing if the the cdcservice is already running. So which command are you doing to stop/terminate cdc-service before running `docker-compose up`

2. I don't think the first 500 lines shows anything interesting. I'd need to see the logfile up to the point the error occurs.

**Comment by bessaleh** [comment]
1- We use **docker-compose up cdc-service --remove-orphans --no-deps -d** command to recreate the container. This command has created a new cdc-service because we had created a new Docker image using eventuate-java-cdc-service-0.12.6.RELEASE.jar which is used in image section in docker-compose file.
We tried many commands: remove container, stop it... using **_docker rm/stop..._**. I'm sure that the container was a new one every time. 
2 - This is the hole logs of the newly cdc: 
 https://drive.google.com/open?id=1VxH1WBAogGeTG0WY1g4dSonQxNHdw1gT
