### ISSUE TITLE
[Feature request] Make kafka settings customizable

### ISSUE THREAD

**Issue by xstefank** [eventuate-local/eventuate-local#44]
In my project utilizing Eventuate Tram [1] I ran into problems with default Kafka settings under high load performance test. 

```2018-04-25 06:09:29.484  INFO 8 --- [erSaga-consumer] o.a.k.c.c.internals.AbstractCoordinator  : Marking the coordinator 172.18.0.5:9092 (id: 2147483647 rack: null) dead for group org.eventuate.saga.orderservice.saga.OrderSaga-consumer
Exception in thread "Eventuate-subscriber-org.eventuate.saga.orderservice.saga.OrderSaga-consumer" java.lang.RuntimeException: org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at io.eventuate.local.java.kafka.consumer.EventuateKafkaConsumer.lambda$start$0(EventuateKafkaConsumer.java:108)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:600)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:541)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:679)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:658)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:167)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.onComplete(ConsumerNetworkClient.java:426)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:278)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:360)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:192)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:426)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1059)
	at io.eventuate.local.java.kafka.consumer.EventuateKafkaConsumer.maybeCommitOffsets(EventuateKafkaConsumer.java:56)
	at io.eventuate.local.java.kafka.consumer.EventuateKafkaConsumer.lambda$start$0(EventuateKafkaConsumer.java:97)
	... 1 more
2018-04-25 06:09:29.506 ERROR 8 --- [erSaga-consumer] i.e.l.j.k.c.EventuateKafkaConsumer       : Got exception: 

org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:600) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:541) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:679) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:658) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:167) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.onComplete(ConsumerNetworkClient.java:426) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:278) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:360) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:192) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:426) ~[kafka-clients-0.10.0.1.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1059) ~[kafka-clients-0.10.0.1.jar!/:na]
	at io.eventuate.local.java.kafka.consumer.EventuateKafkaConsumer.maybeCommitOffsets(EventuateKafkaConsumer.java:56) ~[eventuate-local-java-kafka-0.16.0.RELEASE.jar!/:na]
	at io.eventuate.local.java.kafka.consumer.EventuateKafkaConsumer.lambda$start$0(EventuateKafkaConsumer.java:97) ~[eventuate-local-java-kafka-0.16.0.RELEASE.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
```

A quick search - https://github.com/eventuate-local/eventuate-local/search?utf8=%E2%9C%93&q=session.timeout.ms&type=

If it make sense (I don't have much experience with kafka), it can be beneficial to allow users to customize these settings.

[1] https://github.com/xstefank/eventuate-tram-service

**Comment by cer** [comment]
Sorry for the delayed response. This sounds like a very reasonable suggestion.

**Comment by cer** [comment]
I also think it makes sense to move message processing out of the Kafka message loop. That might be the root cause of the problem.

**Comment by cer** [comment]
For KafkaConsumer configuration, something along the lines of 

```java
@ConfigurationProperties(prefix="eventuate.local.kafka.consumer") {

  private Map<String, String> properties = new HashMap<>();

  public void setProperties(Map<String, String> properties) {
   this.properties = properties;
  }
}
```

will probably work.
