### ISSUE TITLE
NullPointerException when deleting events from events table

### ISSUE THREAD

**Issue by cer** [eventuate-local/eventuate-local#50]
eventuateLocalVersion=0.15.0.RELEASE
CDC docker image version 0.18.0.RELEASE

After deleting some events:

```
DELETE FROM `eventuate`.`events` WHERE  `event_id`='
```
https://github.com/eventuate-local/eventuate-local/blob/0.18.0.RELEASE/eventuate-local-java-embedded-cdc/src/main/java/io/eventuate/local/cdc/debezium/MySqlBinLogBasedEventTableChangesToAggregateTopicRelay.java#L146

```
Caused by: java.lang.RuntimeException: Engine through exceptionStopping connector after error in the application's handler method: null
at io.eventuate.local.cdc.debezium.MySqlBinLogBasedEventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$0(MySqlBinLogBasedEventTableChangesToAggregateTopicRelay.java:96) ~[eventuate-local-java-embedded-cdc-0.15.0-SNAPSHOT.jar!/:na]
at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:742) ~[debezium-embedded-0.3.6.jar!/:0.3.6]
at io.eventuate.local.cdc.debezium.MySqlBinLogBasedEventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$1(MySqlBinLogBasedEventTableChangesToAggregateTopicRelay.java:105) ~[eventuate-local-java-embedded-cdc-0.15.0-SNAPSHOT.jar!/:na]
... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
at io.eventuate.local.cdc.debezium.MySqlBinLogBasedEventTableChangesToAggregateTopicRelay.receiveEvent(MySqlBinLogBasedEventTableChangesToAggregateTopicRelay.java:146) ~[eventuate-local-java-embedded-cdc-0.15.0-SNAPSHOT.jar!/:na]
at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:662) ~[debezium-embedded-0.3.6.jar!/:0.3.6]
```

**Comment by cer** [comment]
Fixed in 0.20.1.RELEASE
