### ISSUE TITLE
CDC fails to start due to SQL error when mysql contains table with dash in name

### ISSUE THREAD

**Issue by KarolisL** [eventuate-local/eventuate-local#6]
We have a table in MySQL, containing dash (`-`), this prevents cdc from reading our events table. 

Tested on `eventuateio/eventuateio-local-cdc-service:0.12.0` docker image.

Am I missing some confugration? 
As I understand, the table name should be escaped in backticks (```), but is there a way to disable process all available tables?

My configuration:
```  - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
          value: zookeeper:2181

        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: com.mysql.jdbc.Driver

        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://hostname/my_table?useUnicode=true&characterEncoding=utf8
        - name: SPRING_DATASOURCE_USERNAME
          value: fssui
        - name: SPRING_DATASOURCE_PASSWORD
          value: <snip>

        - name: EVENTUATELOCAL_CDC_DB_USER_NAME
          value: <snip>
        - name: EVENTUATELOCAL_CDC_DB_PASSWORD
          value: <snip>
        - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
          value: <snip>:9092

```

Exception:
```2017-06-14 14:36:20.921 ERROR 7 --- [y-app-connector] i.d.connector.mysql.SnapshotReader       : Failed due to error: Aborting snapshot after running 'SHOW TABLES IN some-thing': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-thing' at line 1

org.apache.kafka.connect.errors.ConnectException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-thing' at line 1 Error code: 1064; SQLSTATE: 42000.
        at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:141) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
        at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:120) ~[debezium-connector-mysql-0.3.1.jar!/:0.3.1]
        at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:449) [debezium-connector-mysql-0.3.1.jar!/:0.3.1]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-thing' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_91]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_91]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
        at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:306) ~[debezium-core-0.3.1.jar!/:0.3.1]
        at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:287) ~[debezium-core-0.3.1.jar!/:0.3.1]
        at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:253) [debezium-connector-mysql-0.3.1.jar!/:0.3.1]
        ... 1 common frames omitted

```

Log:
[to-gh.txt](https://github.com/eventuate-local/eventuate-local/files/1075482/to-gh.txt)

**Comment by cer** [comment]
Thanks for reporting this. I am investigating.

**Comment by cer** [comment]
Released libraries with the fix: eventuateLocalVersion=0.12.2.RELEASE
The eventuateio/eventuateio-local-cdc-service:0.12.2 is currently building

**Comment by KarolisL** [comment]
Thank you! :-)

**Comment by KarolisL** [comment]
Sorry, I was wrong in the description. Our *database* has `-` in it's name. Still fails with latest release.
