### ISSUE TITLE
Event handler is not consuming messages

### ISSUE THREAD

**Issue by fmicheloni** [eventuate-local/eventuate-local#62]
Hello,

I've set up two Spring Boot applications which are involved in a distributed transaction. When the first application is called, a new Event is inserted into the MySql Database. I expected that the cdc-service would read the MySql logs and publish a message to the Kafka queue, but that doesn't seem to happen.

My current environment consists of my two app, cdc-service, mysql, kafka and zookeeper.

Is there a way to set the logging level of the cdc-service by inserting a new property in the docker-compose?

Do you have any advice for finding out what's happening in this situation?

Thank you,

Fabrizio

**Comment by AhmedSM1** [comment]
I have the same issue and couldnt find an answer have you solved it? if so please tell me how

**Comment by cer** [comment]
There are three things to consider

1. Was a message/event inserted into the database - select count(*) from events
2. Is the CDC service running/correctly configured - what's the cdc service container logs for the 
3. is the consumer correctly processing messages - what's it's log output (for eventuate local setting logging io.eventuate.activity=TRACE will provide detailed information). Also, please note that message/event processing stops if a event/message handler throws an exception

**Comment by AhmedSM1** [comment]
1. yes it is inserted to the database
2. Am not sure. I have the same docker-compose in the Todo sample application and I have configurated it in my application.properties file which is attached
3- No I have exception at io.eventuate.javaclient.domain.EventDispatcher.dispatch(EventDispatcher.java:39)
which mean eventhandler == null but in my subscriber class i have @EnableEventHandlers in my config class and @EventHandlerMethod above each method 
![application Properties](https://user-images.githubusercontent.com/41026810/79145740-d42f7580-7dc9-11ea-9068-93ab6a3b7516.PNG)
![EventDispatcher](https://user-images.githubusercontent.com/41026810/79145759-dabded00-7dc9-11ea-93dc-cbe120a2b254.PNG)
![myMethod](https://user-images.githubusercontent.com/41026810/79145783-e3aebe80-7dc9-11ea-86ee-b7741dfa1e09.PNG)

**Comment by cer** [comment]
If you are getting an exception it's best to include the stack trace.

**Comment by AhmedSM1** [comment]
is having Eureka as service registry have an affect to Kafka and CDC?

**Comment by cer** [comment]
> is having Eureka as service registry have an affect to Kafka and CDC?

No.

**Comment by cer** [comment]
1. Please send stack trace.
2. Does the event type that you are getting an error for have an event handler?
3. Have you enabled logging in the service containing the event handler?

**Comment by cer** [comment]
Also, are you using something that does something with class loading, e.g. Spring Devtools, see https://github.com/eventuate-clients/eventuate-client-java/issues/10#issuecomment-400806283

**Comment by AhmedSM1** [comment]
`java.lang.RuntimeException: No handler for event - subscriberId: Books, class com.ahmed.common.books.BookCreatedEvent
	at io.eventuate.javaclient.domain.EventDispatcher.dispatch(EventDispatcher.java:39) ~[eventuate-client-java-event-handling-0.20.1.RELEASE.jar:na]
	at io.eventuate.javaclient.domain.SwimlaneDispatcher.processQueuedEvent(SwimlaneDispatcher.java:67) ~[eventuate-client-java-event-handling-0.20.1.RELEASE.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_241]

2020-04-13 23:27:56.411 ERROR 28180 --- [pool-1-thread-1] i.e.j.domain.SwimlaneDispatcher          : handler for Books 0  io.eventuate.DispatchedEvent@1d39b659[entityId=000001717539a924-60f6770ba7f70001,eventId=Int128{000001717539a924-60f6770ba7f70000},event=com.ahmed.common.books.BookCreatedEvent@8612fcb5] failed: 

java.lang.RuntimeException: No handler for event - subscriberId: Books, class com.ahmed.common.books.BookCreatedEvent
	at io.eventuate.javaclient.domain.EventDispatcher.dispatch(EventDispatcher.java:39) ~[eventuate-client-java-event-handling-0.20.1.RELEASE.jar:na]
	at io.eventuate.javaclient.domain.SwimlaneDispatcher.processQueuedEvent(SwimlaneDispatcher.java:67) ~[eventuate-client-java-event-handling-0.20.1.RELEASE.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_241]

2020-04-13 23:27:56.412 ERROR 28180 --- [pool-1-thread-1] i.e.l.j.k.c.KafkaMessageProcessor        : Got exception: 

java.lang.RuntimeException: No handler for event - subscriberId: Books, class com.ahmed.common.books.BookCreatedEvent
	at io.eventuate.javaclient.domain.EventDispatcher.dispatch(EventDispatcher.java:39) ~[eventuate-client-java-event-handling-0.20.1.RELEASE.jar:na]
	at io.eventuate.javaclient.domain.SwimlaneDispatcher.processQueuedEvent(SwimlaneDispatcher.java:67) ~[eventuate-client-java-event-handling-0.20.1.RELEASE.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_241]
`

**Comment by AhmedSM1** [comment]
Yes I am using DevTools

**Comment by AhmedSM1** [comment]
Does the event type that you are getting an error for have an event handler? Yes
Have you enabled logging in the service containing the event handler? Yes But the method under @EventHandlerMethod doesnt get executed

**Comment by AhmedSM1** [comment]
Yes it turns out DevTools was the issue !!! Thanks Chris

**Comment by AhmedSM1** [comment]
Cant believe that was the issue Thanks I have spent more than 20 hours trying

**Comment by cer** [comment]
Sorry about that. I've filed a couple of issues #142  and #143
